// Generated by scripts/generate_jinan_demo_fixture.mjs. Do not edit.
// Source: shared/demo_fixture/jinan_big_data_to_inspur.json
import MotoNavigationCore

struct JinanDemoManeuverFixture: Sendable {
    let id: UInt32
    let type: ManeuverType
    let routePointIndex: Int
    let roadName: String
    let instruction: String
}

enum JinanDemoFixture {
    static let fixtureID = "osm-jinan-big-data-d-to-inspur-v2"
    static let routeID = "demo-jinan-big-data-d-to-inspur-v2"
    static let reroutedRouteID = "demo-jinan-big-data-d-to-inspur-v2-rerouted"
    static let destinationPOIID = "B02130VXRE"
    static let fallbackDurationS = 187
    static let roadAttribution = "道路 © OpenStreetMap contributors"

    static let requestedOriginWGS84 = WGS84Point(
        longitudeDeg: 117.1224488,
        latitudeDeg: 36.6748039
    )
    static let requestedDestinationWGS84 = WGS84Point(
        longitudeDeg: 117.1205951,
        latitudeDeg: 36.6624438
    )

    static let routeWGS84: [WGS84Point] = [
        WGS84Point(longitudeDeg: 117.1219266, latitudeDeg: 36.6743309),
        WGS84Point(longitudeDeg: 117.1223594, latitudeDeg: 36.6737036),
        WGS84Point(longitudeDeg: 117.1212204, latitudeDeg: 36.6731529),
        WGS84Point(longitudeDeg: 117.1211380, latitudeDeg: 36.6730626),
        WGS84Point(longitudeDeg: 117.1210354, latitudeDeg: 36.6730032),
        WGS84Point(longitudeDeg: 117.1212676, latitudeDeg: 36.6727170),
        WGS84Point(longitudeDeg: 117.1215946, latitudeDeg: 36.6724025),
        WGS84Point(longitudeDeg: 117.1219050, latitudeDeg: 36.6721550),
        WGS84Point(longitudeDeg: 117.1220838, latitudeDeg: 36.6720308),
        WGS84Point(longitudeDeg: 117.1222155, latitudeDeg: 36.6719384),
        WGS84Point(longitudeDeg: 117.1226384, latitudeDeg: 36.6716737),
        WGS84Point(longitudeDeg: 117.1228715, latitudeDeg: 36.6715623),
        WGS84Point(longitudeDeg: 117.1233231, latitudeDeg: 36.6713895),
        WGS84Point(longitudeDeg: 117.1232567, latitudeDeg: 36.6712722),
        WGS84Point(longitudeDeg: 117.1231233, latitudeDeg: 36.6710017),
        WGS84Point(longitudeDeg: 117.1228356, latitudeDeg: 36.6704194),
        WGS84Point(longitudeDeg: 117.1228181, latitudeDeg: 36.6703840),
        WGS84Point(longitudeDeg: 117.1226853, latitudeDeg: 36.6701137),
        WGS84Point(longitudeDeg: 117.1226653, latitudeDeg: 36.6700719),
        WGS84Point(longitudeDeg: 117.1223286, latitudeDeg: 36.6693688),
        WGS84Point(longitudeDeg: 117.1222655, latitudeDeg: 36.6692268),
        WGS84Point(longitudeDeg: 117.1220587, latitudeDeg: 36.6688176),
        WGS84Point(longitudeDeg: 117.1217042, latitudeDeg: 36.6680844),
        WGS84Point(longitudeDeg: 117.1216972, latitudeDeg: 36.6680681),
        WGS84Point(longitudeDeg: 117.1213496, latitudeDeg: 36.6674164),
        WGS84Point(longitudeDeg: 117.1211971, latitudeDeg: 36.6671116),
        WGS84Point(longitudeDeg: 117.1207878, latitudeDeg: 36.6662939),
        WGS84Point(longitudeDeg: 117.1205047, latitudeDeg: 36.6657769),
        WGS84Point(longitudeDeg: 117.1203986, latitudeDeg: 36.6654951),
        WGS84Point(longitudeDeg: 117.1203991, latitudeDeg: 36.6653932),
        WGS84Point(longitudeDeg: 117.1203759, latitudeDeg: 36.6649895),
        WGS84Point(longitudeDeg: 117.1203831, latitudeDeg: 36.6646713),
        WGS84Point(longitudeDeg: 117.1204061, latitudeDeg: 36.6636719),
        WGS84Point(longitudeDeg: 117.1204098, latitudeDeg: 36.6629987),
        WGS84Point(longitudeDeg: 117.1204105, latitudeDeg: 36.6628981),
    ]

    static let routeGCJ02: [GCJ02Point] = [
        GCJ02Point(longitudeDeg: 117.1280560, latitudeDeg: 36.6747732),
        GCJ02Point(longitudeDeg: 117.1284885, latitudeDeg: 36.6741451),
        GCJ02Point(longitudeDeg: 117.1273501, latitudeDeg: 36.6735951),
        GCJ02Point(longitudeDeg: 117.1272678, latitudeDeg: 36.6735048),
        GCJ02Point(longitudeDeg: 117.1271652, latitudeDeg: 36.6734455),
        GCJ02Point(longitudeDeg: 117.1273972, latitudeDeg: 36.6731589),
        GCJ02Point(longitudeDeg: 117.1277240, latitudeDeg: 36.6728439),
        GCJ02Point(longitudeDeg: 117.1280342, latitudeDeg: 36.6725960),
        GCJ02Point(longitudeDeg: 117.1282129, latitudeDeg: 36.6724715),
        GCJ02Point(longitudeDeg: 117.1283445, latitudeDeg: 36.6723789),
        GCJ02Point(longitudeDeg: 117.1287671, latitudeDeg: 36.6721137),
        GCJ02Point(longitudeDeg: 117.1290000, latitudeDeg: 36.6720020),
        GCJ02Point(longitudeDeg: 117.1294513, latitudeDeg: 36.6718286),
        GCJ02Point(longitudeDeg: 117.1293849, latitudeDeg: 36.6717113),
        GCJ02Point(longitudeDeg: 117.1292515, latitudeDeg: 36.6714408),
        GCJ02Point(longitudeDeg: 117.1289640, latitudeDeg: 36.6708584),
        GCJ02Point(longitudeDeg: 117.1289465, latitudeDeg: 36.6708230),
        GCJ02Point(longitudeDeg: 117.1288137, latitudeDeg: 36.6705527),
        GCJ02Point(longitudeDeg: 117.1287938, latitudeDeg: 36.6705109),
        GCJ02Point(longitudeDeg: 117.1284572, latitudeDeg: 36.6698076),
        GCJ02Point(longitudeDeg: 117.1283941, latitudeDeg: 36.6696656),
        GCJ02Point(longitudeDeg: 117.1281874, latitudeDeg: 36.6692564),
        GCJ02Point(longitudeDeg: 117.1278330, latitudeDeg: 36.6685230),
        GCJ02Point(longitudeDeg: 117.1278260, latitudeDeg: 36.6685067),
        GCJ02Point(longitudeDeg: 117.1274786, latitudeDeg: 36.6678550),
        GCJ02Point(longitudeDeg: 117.1273261, latitudeDeg: 36.6675501),
        GCJ02Point(longitudeDeg: 117.1269170, latitudeDeg: 36.6667323),
        GCJ02Point(longitudeDeg: 117.1266340, latitudeDeg: 36.6662152),
        GCJ02Point(longitudeDeg: 117.1265279, latitudeDeg: 36.6659333),
        GCJ02Point(longitudeDeg: 117.1265284, latitudeDeg: 36.6658314),
        GCJ02Point(longitudeDeg: 117.1265052, latitudeDeg: 36.6654274),
        GCJ02Point(longitudeDeg: 117.1265123, latitudeDeg: 36.6651090),
        GCJ02Point(longitudeDeg: 117.1265352, latitudeDeg: 36.6641090),
        GCJ02Point(longitudeDeg: 117.1265388, latitudeDeg: 36.6634354),
        GCJ02Point(longitudeDeg: 117.1265395, latitudeDeg: 36.6633347),
    ]

    static let maneuvers: [JinanDemoManeuverFixture] = [
        JinanDemoManeuverFixture(id: 1, type: .continue, routePointIndex: 0, roadName: "园区道路", instruction: "沿园区道路驶向新泺大街"),
        JinanDemoManeuverFixture(id: 2, type: .right, routePointIndex: 1, roadName: "新泺大街", instruction: "右转进入新泺大街"),
        JinanDemoManeuverFixture(id: 3, type: .left, routePointIndex: 4, roadName: "崇华路", instruction: "左转进入崇华路"),
        JinanDemoManeuverFixture(id: 4, type: .right, routePointIndex: 12, roadName: "浪潮路", instruction: "右转进入浪潮路"),
        JinanDemoManeuverFixture(id: 5, type: .arrive, routePointIndex: 34, roadName: "浪潮集团(总部)", instruction: "到达浪潮集团(总部)附近"),
    ]
}
